### ISSUE TITLE
Data/Feature download command

### ISSUE THREAD

**Issue by ardarslan** [JonnyS1226/ego4d_asl#1]
Hi,

Thank you for your contribution. Could you please provide the bash command for downloading data and features for the MQ task? I was planning to use the following:

`
ego4d --output_directory="ego4d_data" --datasets clips annotations omnivore_video_swinl slowfast8x8_r101_k400 --benchmarks mq --version v2
`

Best regards,
Arda

**Comment by JonnyS1226** [comment]
Sure. You can download slowfast and omnivore features by the command you mentioned.  EgoVLP and InternVideo features can be downloaded from [egovlp train&val](https://drive.google.com/file/d/1-HEUCdyfNX7CBZhz40yiyTr7to_p7wUi/view) , [egovlp test](https://drive.google.com/file/d/1-JmezY3eIkHKJ1JBA_AA8QWBoY3W2HpS/view) and [internvideo](https://zenodo.org/record/7340838). Combination of features will achieve a better result.
We will update instructions in readme later.

**Comment by ardarslan** [comment]
Thank you for your prompt reply. Is it also true that I should download "clips" and not the "full scale" videos?

**Comment by JonnyS1226** [comment]
yes, no need to download full-scale videos if you only want to tackle MQ or NLQ tasks based on this codebase.

**Comment by ardarslan** [comment]
Thanks a lot once again!

**Comment by ardarslan** [comment]
This will probably be mentioned in the update in the README but could you please tell how can I construct the features in 
"/sdb/sjy/projects/ego4d/v1/slowfast_clip" and "/sdb/sjy/projects/ego4d/v1/omnivore_clip"? As far as I understood, the features I downloaded using the bash command above are extracted using untrimmed 30 FPS canonical videos, and for each clip, I should simply crop these features and save them as .pt files in these two directories.

Edit: https://github.com/happyharrycn/actionformer_release/blob/main/tools/convert_ego4d_trainval.py
I think this script does what I'm looking for. The problem is solved for now, thank you anyway!
